config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :recipes do
    member do
      get 'like'
    end
  end
  resources :users do
    member do
      get 'followings'
      get 'followers'
      get 'timeline'
      get 'like'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    validates :image, presence: true
    validates :title, presence: true, length: { maximum: 30 }
    validates :description, presence: true, length: { maximum: 60 }
    
    belongs_to :user
    has_many :recipe_materials
    has_many :recipe_steps
    has_many :recipe_points
    
    has_many :likes
    has_many :liking_users, through: :likes, source: :user
    
    accepts_nested_attributes_for :recipe_materials, allow_destroy: true
    accepts_nested_attributes_for :recipe_steps, allow_destroy: true
    accepts_nested_attributes_for :recipe_points, reject_if: :all_blank, allow_destroy: true
    
    mount_uploader :image, ImageUploader

end

app/models/recipe_material.rb
class RecipeMaterial < ActiveRecord::Base
    belongs_to :recipe
    validates :material, :quantity, presence: true
end

app/models/recipe_point.rb
class RecipePoint < ActiveRecord::Base
    belongs_to :recipe
    validates :point, presence: true
end

app/models/recipe_step.rb
class RecipeStep < ActiveRecord::Base
  belongs_to :recipe
  validates :step, presence: true
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = self.email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :recipes
    
    has_many :following_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
    has_many :following_users, through: :following_relationships, source: :followed
    
    has_many :follower_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
    has_many :follower_users, through: :follower_relationships, source: :follower
    
    has_many :likes
    has_many :like_recipes, through: :likes, source: :recipe
    
    mount_uploader :image, ImageUploader
    
    # 他のユーザーをフォローする
    def follow(other_user)
        following_relationships.find_or_create_by(followed_id: other_user.id)
    end

    # フォローしているユーザーをアンフォローする
    def unfollow(other_user)
        following_relationship = following_relationships.find_by(followed_id: other_user.id)
        following_relationship.destroy if following_relationship
    end

    # あるユーザーをフォローしているかどうか？
    def following?(other_user)
        following_users.include?(other_user)
    end
    
    def feed_items
        Recipe.where(user_id: following_user_ids + [self.id])
    end

    def like?(recipe)
        like_recipes.include?(recipe)
    end
    
    def like!(recipe)
        likes.find_or_create_by(recipe_id: recipe.id)
    end
    
    def unlike!(recipe)
        likes.find_by(recipe_id: recipe.id).destroy
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "ログインしてください"
      redirect_to login_url
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @like = current_user.likes.build(recipe_id: params[:recipe_id])
        @like.save
        redirect_to :back
    end
    
    def destroy
        @like = current_user.likes.find_by(recipe_id: params[:id])
        @like.destroy
        redirect_to :back
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :set_recipe, only: [:show, :edit, :update, :destroy, :like]
    before_action :logged_in_user, only: [:new, :create, :edit, :update]
    def index
        @recipe = Recipe.all.order(created_at: :desc)
        @q = Recipe.ransack(params[:q])
        @recipe = @q.result.includes([:recipe_materials]).uniq
    end
    
    def show
    end
    
    def new
        @recipe = Recipe.new
        3.times { @recipe.recipe_materials.build }
        4.times { @recipe.recipe_steps.build }
        @recipe.recipe_points.build
    end
    
    def create
        @recipe = current_user.recipes.build(recipe_params)
        if @recipe.save
            flash[:success] = "投稿に成功しました"
            redirect_to @recipe
        else
            render 'new'
        end
    end
    
    def edit
    end
     
    def update
        if @recipe.update(recipe_params)
            redirect_to recipe_path, notice: "レシピを変更しました。"
        else
            render 'edit'
        end
    end
    
    def destroy
        @recipe.destroy
        redirect_to root_path
    end
    
    def like
        @like_users = @recipe.liking_users
    end
    
    def recipe_params
        params.require(:recipe).permit(:title, :description, :image, :image_cache, recipe_materials_attributes: [:id, :material, :quantity, :_destroy], recipe_steps_attributes: [:id, :step, :_destroy], recipe_points_attributes: [:id, :point, :_destroy])
    end
    
    def set_recipe
        @recipe = Recipe.find(params[:id])
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :logged_in_user

    def create
        @user = User.find(params[:followed_id])
        current_user.follow(@user)
    end

    def destroy
        @user = current_user.following_relationships.find(params[:id]).followed
        current_user.unfollow(@user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "ログインしました"
      redirect_to @user
    else
      flash[:danger] = "メールアドレスもしくはパスワードが正しくありません"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :followers, :followings, :timeline, :like]
  before_action :authenticate, only: [:edit, :update]
  before_action :logged_in_user, only: [:timeline]
  
  def index
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def show
    @recipes = @user.recipes.order(created_at: :desc)
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      redirect_to user_path, notice: "プロフィールを変更しました。"
    else
      render 'edit'
    end
  end
  
  def followers
    @follower_users = @user.follower_users
  end
  
  def followings
    @following_users = @user.following_users
  end
  
  def timeline
    if logged_in?
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
    end
  end
  
  def like
    @like_recipes = @user.like_recipes.order(created_at: :desc)
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :introduction, :image, :image_cache)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def authenticate
    redirect_to root_url unless @user == current_user
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_materials_helper.rb
module RecipeMaterialsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end
    
    def store_location
        session[:forwarding_url] = request.url if request.get?
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container footer-frame">
        <div class="footer-title">
            <%= link_to "Kitchen", root_path %>
        </div>
        <div class="developer-data">
            <div class="developer-name">
                developer：somakihiro
            </div>
            <div class="developer-twitter">
                <a href="https://twitter.com/somakihiro" target="_blank">Twitter</a>
            </div>
            <div class="developer-facebook">
                <a href="https://www.facebook.com/akihiro.soma.54" target="_blank">Facebook</a>
            </div>
        </div>
    </div>
</fotter>

app/views/layouts/_header.html.erb
<header>
    <div class="header-title">
        <%= link_to "Kitchen", root_path %>
    </div>
    <div class="header-right">
        <% if logged_in? %>
            <ul class="nav nav-pills">
                <li role="presentation" class="dropdown header-user-name">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                        <%= current_user.name %><span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li role="presentation"><%= link_to "マイページ", current_user %></li>
                        <li role="presentation"><%= link_to "レシピ作成", new_recipe_path %></li>
                        <li role="presentation"><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>
                        <li role="presentation"><%= link_to "タイムライン", timeline_user_path(current_user) %></li>
                        <li role="presentation"><%= link_to "ログアウト", logout_path, method: "delete" %></li>
                    </ul>
                </li>
            </ul>
        <% else %>
            <div class="header-signup-link">
                <%= link_to "アカウント作成", signup_path %>
            </div>
            <div class="header-login-link">
                <%= link_to "ログイン", login_path %>
            </div>
        <% end %>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kitchen</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container sb-site">
    <div class="row main">
        <%= yield %>
    </div>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <%= f.label "写真を載せよう！" %>
        <%= image_tag @recipe.image.thumb.url if @recipe.image? %>
        <%= f.file_field :image %>
        <%= f.hidden_field :image_cache %>
    </div>
    <div class="field">
        <%= f.text_field :title, class: "form-control", placeholder: "料理名をつけよう！(30文字以内)" %>
    </div>
    <div class="field">
        <%= f.text_area :description, class: "form-control", placeholder: "料理の魅力を伝えよう！(60文字以内)" %>
    </div>
    <div class="field">
        <%= f.label :material %>
        <%= f.label :quantity %>
        <%= f.fields_for :recipe_materials do |material| %>
            <%= render 'recipes/recipe_material_fields', f: material %>
        <% end %>
        <div class="field">
            <%= link_to_add_association '材料を追加', f, :recipe_materials, class: "btn btn-primary" %>
        </div>
    </div>
    <div class="field new-recipe-step-frame">
        <%= f.label :step %>
        <%= f.fields_for :recipe_steps do |step| %>
            <%= render 'recipes/recipe_step_fields', f: step %>
        <% end %>
        <div class="field">
            <%= link_to_add_association 'レシピ追加', f, :recipe_steps, class: "btn btn-primary" %>
        </div>
    </div>
    <div class="field new-recipe-point-frame">
        <%= f.label :point %>
        <%= f.fields_for :recipe_points do |point| %>
            <%= render 'recipes/recipe_point_fields', f: point %>
        <% end %>
        <div class="field">
            <%= link_to_add_association 'ポイント追加', f, :recipe_points, class: "btn btn-primary" %>
        </div>
    </div>
    <%= f.submit "投稿する", class: "btn btn-large btn-warning new-recipe-btn" %>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="user-recipe-image col-md-4">
    <div class="recipe-thumb-frame">
        <%= link_to recipe.title, recipe, class: "users-recipe-title" %>
        <%= image_tag(recipe.image, { class: "recipe-thumb"}) %>
    </div>
</div>

app/views/recipes/_recipe_material_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.text_field :material, class: "form-control material-form", placeholder: "じゃがいも" %>
        <%= f.text_field :quantity, class: "form-control quantity-form", placeholder: "2個" %>
    </div>
    <div class="field remove-association-btn">
        <%= link_to_remove_association "削除", f %>
    </div>
</div>

app/views/recipes/_recipe_point_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.text_field :point, class: "form-control point-form", placeholder: "料理のポイントを書こう！" %>
    </div>
    <div class="field remove-association-btn">
        <%= link_to_remove_association "削除", f %>
    </div>
</div>

app/views/recipes/_recipe_step_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.text_area :step, class: "form-control step-form", placeholder: "レシピを書こう！" %>
    </div>
    <div class="field remove-association-btn">
        <%= link_to_remove_association "削除", f %>
    </div>
</div>

app/views/recipes/edit.html.erb
<h2>レシピの編集</h2>
<div class="field">
    <%= render 'form' %>
</div>

app/views/recipes/index.html.erb
<div class="row">
    <%= search_form_for(@q, method: :get) do |f| %>
        <%= f.search_field :title_or_recipe_materials_material_cont, class: "recipes-search form-control", placeholder: "レシピ名, 材料名" %>
    <% end %>
    <h3 class="recipes-list col-md-12">レシピ一覧</h3>
    <% @recipe.each_slice(4) do |recipes| %>
        <div class="row top-recipes-frame">
            <% recipes.each do |recipe| %>
                <div class="top-recipes col-md-3">
                    <div class="top-recipes-image">
                        <%= link_to image_tag(recipe.image.url, { class: "top-recipe-thumb" }), recipe %>
                    </div>
                    <div class="top-recipes-title">
                        <%= link_to recipe.title, recipe, class: "top-recipes-title-link" %>
                    </div>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

app/views/recipes/like.html.erb
<h3>「<%= @recipe.title %>」にいいね！しているユーザー</h3>
<div class="row like-users-list">
    <% if @like_users.any? %>
        <% @like_users.each do |user| %>
            <div class="col-md-3 like-users-frame">
                <div class="like-users-thumb">
                    <% if user.image? %>
                        <%= link_to image_tag(user.image.url, { class: "like-users-image" }), user %>
                    <% else %>
                        <%= link_to image_tag("default_image.jpg", { class: "like-users-image" }), user %>
                    <% end %>
                </div>
                <div class="like-users-name">
                    <%= link_to user.name, user %>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/recipes/new.html.erb
<h2 class="new-recipe-top">レシピを投稿しよう</h2>
<div class="field">
    <%= render 'form' %>
</div>

app/views/recipes/show.html.erb
<% if current_user == @recipe.user %>
    <%= link_to "レシピ編集", edit_recipe_path, class: "btn btn-large btn-primary" %>
    <%= link_to "レシピ削除", recipe_path, class: "btn btn-large btn-primary", method: :delete, data: { confirm: '本当に削除してもよろしいですか？' } %>
<% end %>
<div class="recipe-option">
<div class="chef-name">
    シェフ：<%= link_to @recipe.user.name, @recipe.user, class: "chef-name-link" %>
</div>
    <div class="like-btn">
        <% if logged_in? %>
            <% if current_user.like?(@recipe) %>
                <%= link_to "お気に入り解除", like_path(@recipe), method: :delete, class: "btn btn btn-primary" %>
            <% else %>
                <%= link_to "お気に入りにする", likes_path(recipe_id: @recipe.id), method: :post, class: "btn btn-warning" %>
            <% end %>
        <% end %>
        <div class="like-recipe-count">
            <%= link_to "お気に入り" + @recipe.likes.count.to_s + "件", like_recipe_path %>
        </div>
    </div>
</div>
<div class="recipe-top row">
    <%= image_tag @recipe.image.url, class: "recipe-image" %>
    <div class="recipe-top-bottom">
        <div class="recipe-title">
            <%= @recipe.title %>
        </div>
        <div class="recipe-description">
            <%= @recipe.description %>
        </div>
    </div>
</div>
<div class="row">
    <div class="recipe-element col-md-6">
        <div class="recipe-subtitle">
            材料
        </div>
        <% @recipe.recipe_materials.each do |material| %>
            <div class="recipe-material-id">
                <span><%= material.material %></span>
                <span class="quantity"><%= material.quantity %></span>
            </div>
        <% end %>
    </div>
    <div class="recipe-element col-md-6">
        <div class="recipe-subtitle">
            ポイント
        </div>
        <ul>
            <% @recipe.recipe_points.each do |point| %>
                <li><%= point.point %></li>
            <% end %>
        </ul>
    </div>
</div>
<div class=" recipe-element row col-md-12">
    <div class="recipe-subtitle">
        レシピ
    </div>
    <ol>
        <% @recipe.recipe_steps.each do |step| %>
            <div class="recipe-step-id col-md-6">
                <li><%= step.step %></li>
            </div>
        <% end %>
    </ol>
</div>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
    <div id="follow_form">
        <% if current_user.following?(@user) %>
            <%= render 'unfollow' %>
        <% else %>
            <%= render 'follow' %>
        <% end %>
    </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォロー中", class: "btn btn-info" %>
<% end %>

app/views/users/edit.html.erb
<h2>プロフィールを編集</h2>
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :image %>
    <div class="field">
        <%= image_tag @user.image.thumb.url if @user.image? %>
        <%= f.file_field :image %>
        <%= f.hidden_field :image_cache %>
    </div>
    <%= f.label :name %>
    <div class="field">
        <%= f.text_field :name, class: "form-control" %>
    </div>
    <%= f.label :email %>
    <div class="field">
        <%= f.email_field :email, class: "form-control" %>
    </div>
    <%= f.label :introduction %>
    <div class="field">
        <%= f.text_area :introduction, class: "form-control" %>
    </div>
    <div class="field">
        <%= f.submit "保存", class: "btn btn-large btn-primary edit-user-btn" %>
    </div>
<% end %>

app/views/users/followers.html.erb
<h3>フォロワー</h3>
<div class="row follower-list">
    <% if @follower_users.any? %>
        <% @follower_users.each do |follower| %>
            <div class="col-md-3 follower-frame">
                <div class="follower-thumb">
                    <% if follower.image? %>
                        <%= link_to image_tag(follower.image.url, { class: "follower-image" }), follower %>
                    <% else %>
                        <%= link_to image_tag("default_image.jpg", { class: "follower-image" }), follower %>
                    <% end %>
                </div>
                <div class="follower-name">
                    <%= link_to follower.name, follower %>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/users/followings.html.erb
<h3>フォロー中</h3>
<div class="row following-list">
    <% if @following_users.any? %>
        <% @following_users.each do |following| %>
            <div class="col-md-3 following-frame">
                <div class="following-thumb">
                    <% if following.image? %>
                        <%= link_to image_tag(following.image.url, { class: "following-image" }), following %>
                    <% else %>
                        <%= link_to image_tag("default_image.jpg", { class: "following-image" }), following %>
                    <% end %>
                </div>
                <div class="following-name">
                    <%= link_to following.name, following %>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/users/like.html.erb
<h3 class="like-recipes col-md-12"><%= @user.name %>さんのお気に入りレシピ</h3>
<% @like_recipes.each do |recipe| %>
    <div class="like-recipe-image col-md-4">
        <div class="like-recipe-thumb-frame">
            <%= link_to recipe.title, recipe, class: "like-recipe-title" %>
            <%= image_tag(recipe.image, { class: "like-recipe-thumb"}) %>
        </div>
    </div>
<% end %>

app/views/users/new.html.erb
<h2 class="new-user-title">Kitchenを始めよう</h2>
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <%= f.text_field :name, class: "form-control", placeholder: "ユーザー名" %>
    </div>
    <div class="field">
        <%= f.email_field :email, class: "form-control", placeholder: "メールアドレス" %>
    </div>
    <div class="field">
        <%= f.password_field :password, class: "form-control", placeholder: "パスワード" %>
    </div>
    <div class="field">
        <%= f.submit "アカウント作成", class: "btn btn-large btn-primary new-user-btn" %>
    </div>
    <span>アカウントをお持ちですか？</span>
    <%= link_to "ログイン", login_path, { class: "signup-link" } %>
<% end %>

app/views/users/show.html.erb
<div class="user-profile">
    <div class="profile-left col-md-4">
        <% if @user.image? %>
            <%= image_tag @user.image.url, class: "user-image" %>
        <% else %>
            <%= image_tag "default_image.jpg", class: "user-image" %>
        <% end %>
    </div>
    <div class="profile-right col-md-6">
        <div class="profile-right-top">
            <span class="profile-name">
                <%= @user.name %>
            </span>
            <% if @user == current_user %>
                <div class="profile-edit">
                    <%= link_to "プロフィール編集", edit_user_path, class: "btn btn-large btn-primary edit-profile-btn" %>
                </div>
            <% end %>
            <%= render 'follow_form' if logged_in? %>
        </div>
        <div class="profile-introduction">
            <% if @user.introduction.present? %>
                <%= @user.introduction %>
            <% end %>
        </div>
        <div class="users-data">
            <span>レシピ投稿<%= @user.recipes.count %>件</span>
            <%= link_to "お気に入り" + @user.like_recipes.count.to_s+ "件", like_user_path, class: "users-like-data" %>
            <%= link_to "フォロワー" + @user.follower_relationships.count.to_s + "人", followers_user_path, class: "users-follow-data" %>
            <%= link_to @user.following_relationships.count.to_s + "人をフォロー中", followings_user_path, class: "users-follow-data" %>
        </div>
    </div>
</div>
<div class="user-recipes col-md-12">
    <%= render @recipes %>
</div>

app/views/users/timeline.html.erb
<% if logged_in? %>
    <% if @feed_items.any? %>
        <% @feed_items.each do |items| %>
            <div class="items-frame">
                <div class="items-user">
                    <div class="items-user-main">
                        <% if items.user.image? %>
                            <%= link_to image_tag(items.user.image.url, { class: "items-user-image" }), items.user %>
                        <% else %>
                            <%= link_to image_tag("default_image.jpg", { class: "items-user-image" }), items.user %>
                        <% end %>
                        <%= link_to items.user.name, items.user %>
                    </div>
                    <div class="items-timestamp">
                        <%= time_ago_in_words(items.created_at) %>前
                    </div>
                </div>
                <div class="items-image">
                    <%= link_to image_tag(items.image.url, { class: "items-thumb" }), items %>
                </div>
                <div class="feed-items">
                    <%= link_to items.title, items, class: "items-title" %>
                    <% if logged_in? %>
                        <div class="like-btn">
                            <% if current_user.like?(items) %>
                                <%= link_to "いいね解除", like_path(items), method: :delete, class: "btn btn btn-primary" %>
                            <% else %>
                                <%= link_to "いいね！", likes_path(recipe_id: items.id), method: :post, class: "btn btn-warning" %>
                            <% end %>
                        </div>
                    <% end %>
                </div>
            </div>
        <% end %>
    <% end %>
<% end %>